### PR TITLE
fix: prevent focusing the output tab

### PR DESCRIPTION
**Pull request by d0x2f**
Hi,

Just a quick one to prevent the extension from stealing focus to the output tab.

These issues seem relevant: #450 #144 #65

### CODE REVIEW

**Comment by ilyahoilik** [comment]
@felixfbecker

**Comment by barnesheaton** [comment]
@felixfbecker

**Comment by ahinkle** [comment]
@felixfbecker

**Comment by Jupadr** [comment]
@felixfbecker

**Comment by zacscott** [comment]
Please, please accept this. This is the single most annoying thing I have to deal with on a daily basis

**Comment by vielhuber** [comment]
Please release.

**Comment by elgandoz** [comment]
Please indeed. Every time I need to reload the window (which is several time a day) the output tabs repeatedly shows up, shouting in your face every single php file parsed. Hiding the panel and/or the tab is pointless, the panel will display anyway. 
The extension is awesome, but this bug is nerve-wracking.

**Comment by zacscott** [comment]
@felixfbecker

**Comment by ilyahoilik** [comment]
@felixfbecker

**Comment by elgandoz** [comment]
I would recommend to compile the extension on your own from the d0x2f fork. It takes one minute and it does the job. From the root of the repo:
```shell
composer install
npm install -g vsce && npm install
npm run build
vsce package
```
You'll find `php-intellisense-1.5.4.vsix`. The version won't match unless you edit the manifest, but it doesn't matter. Install via VSIX, from the Extensions menu.

**Comment by bbceg** [comment]
I had a bit of a shocker trying to get @elgandoz suggestion to work on WSL (and then on Git Bash). I had to run the following on WSL (the key being the --unsafe-perm):

`composer install
sudo npm install -g vsce && sudo npm install --unsafe-perm
sudo run build
sudo vsce package'

I suspect the issue is related to how WSL handles permissions although that doesn't explain why Git Bash didn't work. Hopefully this helps someone all the same.

**Pull request merged**
