### PR TITLE
feat: PHP version manager support

### PR DESCRIPTION
**Pull request by benallfree**
This PR sets the current working directory of the child process so PHP version managers work correctly.

By default, the child process current working directory is process.cwd(), which might not always be in the project tree. For PHP version managers, php needs to be executed inside the project tree so the `.phpversion` (or whatever similar file) is detected correctly. The solution is to set the child process cwd to `vscode.workspace.rootPath`.

For example, .phpversion inside my project is set to `7.1.3`. But outside my project tree, PHP version is `5.3`. Here is my mampenv package that allows a `.phpversion` file to be specified in the root of the project, much like rbenv etc.: https://github.com/benallfree/mampenv

This will also work for multiple project roots that have different `.phpversion` files.

This seems to work for me for a single workspace. For a more advanced solution, please see the `phpfmt` extension: https://github.com/kokororin/vscode-phpfmt/blob/master/src/PHPFmt.ts#L122

### CODE REVIEW

**Comment by felixfbecker** [comment]
What is the purpose/benefit of running the language server with the PHP version that the project is targeting? Consider that if that version is PHP 5, the language server will not work

**Comment by benallfree** [comment]
Your extension already checks for minimum version requirements. The benefit that we don't have to rely on a default version, which could be 5.x or something else.

**Comment by felixfbecker** [comment]
So after this PR, it would be impossible to run the extension on a project that uses PHP 5, right? Whereas before it worked if your global default version was PHP 7

**Comment by benallfree** [comment]
`validate.executablePath` can point directly to a PHP7 binary in that case. And that's fine because the least-surprise expectation is for `php` to be the shim version.

Incidentally, this extension might benefit from preferring `validate.executablePath` over the more generic `php.executablePath`. If your example actually happened, it might be the case that other things are relying upon a shimmed `php` from `php.executablePath`.

```
const executablePath =
        conf.get<string>('executablePath') ||
        conf.get<string>('validate.executablePath')
```

**Comment by benallfree** [comment]
If changing the current behavior feels too risky, we could add this as a switch, like `version.setCwdToProjectRoot` or something?

**Pull request closed without merging**
