### PR TITLE
Add Debug section to README.md

### PR DESCRIPTION
**Pull request by mniewrzal**

### CODE REVIEW

**Comment by felixfbecker** [comment]
I don't know wether this belongs here - this extension is just written in TypeScript. We could add it in language-server, but I don't think we should advocate a specific debugger. I have a walkthrough at https://github.com/felixfbecker/vscode-php-debug#installation for my PHP debugger, maybe we could just link to that and to the Eclipse docs?

**Comment by mniewrzal** [comment]
Ok, maybe just links to other docs will be better solution. I think this repository will be entry point for potential contributors and some info about debugging would be useful. For Eclipse link to https://wiki.eclipse.org/Debugging_using_XDebug can be added, its not perfect but I don't have anything better right now :)

**Comment by felixfbecker** [comment]
I already updated the package.json so the issues point directly to language-server. I think we should just highlight in bold that this is just the VS Code extension and not the language server. But +1 for more contribution guidelines in the language-server repo.

**Comment by mniewrzal** [comment]
Sounds good :+1:

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/vscode-php-intellisense/commit/fcc312e6da85272e043199d8cf888ac6d5c133ff

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues/13

**Pull request closed without merging**
